// Sidebar order per channel; `placement: 'footer'` entries sit under the divider at the
// bottom and are shown in both channels.
export const pages = [
  {
    id: 'discovery',
    label: 'Локальный парсер',
    eyebrow: 'SMM РЕСУРСЫ',
    title: 'Локальный парсер',
    description: '',
    placement: 'main',
    channel: 'instagram',
  },
  {
    id: 'outreach',
    label: 'Первичная рассылка',
    eyebrow: 'АККАУНТЫ',
    title: 'Первичная рассылка',
    description: '',
    placement: 'main',
    channel: 'instagram',
  },
  {
    id: 'profiles',
    label: 'Аккаунты',
    eyebrow: 'INSTAGRAM',
    title: 'Аккаунты',
    description: 'Отдельная сессия, cookies и прокси для каждого профиля.',
    placement: 'main',
    channel: 'instagram',
  },
  {
    id: 'leads',
    label: 'База артистов',
    eyebrow: 'КОНТАКТЫ',
    title: 'База артистов',
    description: 'Все собранные профили, сигналы и статусы в одном месте.',
    placement: 'main',
    channel: 'instagram',
  },
  {
    id: 'history',
    label: 'История',
    eyebrow: 'ЗАПУСКИ',
    title: 'История поисков',
    description: 'Результаты и состояние прошедших поисков.',
    placement: 'main',
    channel: 'instagram',
  },
  {
    id: 'dashboard',
    label: 'Статистика',
    eyebrow: 'ОБЗОР',
    title: 'Статистика',
    description: 'Что происходит с поисками, артистами и вашей базой.',
    placement: 'main',
    channel: 'instagram',
  },
  {
    id: 'crm',
    label: 'CRM',
    eyebrow: 'INSTAGRAM',
    title: 'CRM Instagram',
    description: 'Контакты, статусы, следующие шаги и деньги в одной рабочей таблице.',
    placement: 'main',
    channel: 'instagram',
  },
  {
    id: 'imessage',
    label: 'Кампании',
    eyebrow: 'IMESSAGE',
    title: 'Кампании iMessage',
    description: 'Рассылка с вашего iPhone через Команды так же понятно, как в Instagram.',
    placement: 'main',
    channel: 'imessage',
  },
  {
    id: 'imessage-log',
    label: 'Логи',
    eyebrow: 'IMESSAGE',
    title: 'Логи iMessage',
    description: 'Каждый шаг моста и Shortcut с точным статусом.',
    placement: 'main',
    channel: 'imessage',
  },
  {
    id: 'imessage-crm',
    label: 'CRM',
    eyebrow: 'IMESSAGE',
    title: 'CRM iMessage',
    description: 'Телефоны и email, статусы, следующие шаги и деньги в одной рабочей таблице.',
    placement: 'main',
    channel: 'imessage',
  },
  {
    id: 'settings',
    label: 'Настройки',
    eyebrow: 'ПАРАМЕТРЫ',
    title: 'Настройки',
    description: 'Темп сбора, параметры оценки и локальные данные.',
    placement: 'footer',
    channel: 'instagram',
  },
] as const;
export type PageId = (typeof pages)[number]['id'];
export type Channel = (typeof pages)[number]['channel'];
export const channels: { id: Channel; label: string; section: string }[] = [
  { id: 'instagram', label: 'Instagram', section: 'INSTAGRAM' },
  { id: 'imessage', label: 'iMessage', section: 'IMESSAGE' },
];
