// Builds the Apple emoji set of the CRM status picker: copies the 64px PNGs of the chosen
// emoji from an unpacked emoji-datasource-apple package into frontend/src/assets/emoji and
// writes frontend/src/components/crm/emojiSet.ts.
// Usage: node scripts/build-emoji.mjs <path to emoji-datasource-apple/package>
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const groups = [
  [
    'Смайлы',
    '😀😃😄😁😆😅😂🤣😊😇🙂😉😍🥰😘😋😛😜🤪😎🤩🥳😏😒😞😔😟😕🙁😣😖😫😩🥺😢😭😤😠😡🤬🤯😳🥵🥶😱😨😰😥😓🤗🤔🤭🤫😶😐😑😬🙄😯😮😲🥱😴🤤😵🤐🥴🤢🤮🤧😷🤒🤑🤠😈👿🤡💩👻💀👽🤖🎃',
  ],
  [
    'Жесты и люди',
    '👍👎👌🤌🤏✌️🤞🤟🤘🤙👈👉👆👇☝️✋🖐️🖖👋👏🙌🤲🤝🙏✍️💪👀🧠🫶🙋🙅🙆🤷🤦💁🙇🕺💃👯🧑‍💻🧑‍🎤🧑‍💼🕵️👑',
  ],
  [
    'Символы',
    '❤️🧡💛💚💙💜🖤🤍🤎💔❣️💕💞💓💗💖💘💝💯💢💥💫💦💨💬💭💤✅☑️✔️❌❎➕➖❗❓‼️⁉️⚠️🚫⛔📛🔞🆗🆕🆓🆒🆙🔝🔥⭐🌟✨⚡💎🔴🟠🟡🟢🔵🟣⚫⚪🟤🔺🔻🔶🔷▶️⏸️⏹️⏺️⏭️🔁🔄♻️🔔🔕',
  ],
  [
    'Музыка',
    '🎵🎶🎤🎧🎼🎹🥁🎷🎺🎸🪕🎻📻🎙️🎚️🎛️💿📀🎬🎥📹🎞️🎨🎭🎪🎟️🎫🏆🥇🥈🥉🏅🎖️🎯🎲🎮🕹️🎉🎊🎁🎈',
  ],
  [
    'Деньги и дела',
    '💰💵💴💶💷💸💳🧾💹📈📉📊💼📁📂🗂️📅📆🗓️📌📍📎📝✏️🖊️📋📞☎️📱📲💻🖥️⌨️📧📨📩📤📥📦📫📮✉️🔗🔒🔓🔑🗝️🔨🛠️⚙️🧲⏰⏳⌛💡🔍📣📢',
  ],
  [
    'Природа и еда',
    '🌈☀️🌙🌊🌸🌹🌺🌻🌴🍀🍁🐐🦁🐍🦄🐝🦋🐶🐱🐼🦊🐸🍕🍔🍟🌮🍣🍩🍪🎂🍰🍫🍿☕🍺🍻🥂🍾🍷🥃🍸🍹',
  ],
  [
    'Места и флаги',
    '🚀✈️🚗🏎️🏍️🚕🛸🚁⛵🏠🏢🏙️🌃🌆🗽🗼🏝️🌍🌎🌏🗺️🧭⛰️🏁🚩🏳️🏴🇺🇸🇬🇧🇷🇺🇺🇦🇰🇿🇫🇷🇩🇪🇧🇷🇯🇵🇰🇷🇨🇦🇳🇬🇿🇦',
  ],
];

const source = resolve(process.argv[2] ?? '');
const root = resolve(import.meta.dirname, '..');
const out = join(root, 'frontend/src/assets/emoji');
const data = JSON.parse(readFileSync(join(source, 'emoji.json'), 'utf8'));

/** File key of an emoji: its code points without the FE0F variation selector. */
const keyOf = text =>
  [...text]
    .map(char => char.codePointAt(0).toString(16))
    .filter(code => code !== 'fe0f')
    .join('-');
const byKey = new Map();
for (const item of data) {
  if (!item.has_img_apple) continue;
  for (const unified of [item.unified, item.non_qualified].filter(Boolean)) {
    byKey.set(unified.toLowerCase().split('-').filter(c => c !== 'fe0f').join('-'), item);
  }
}

// One emoji is a grapheme: ZWJ sequences, flags and FE0F stay together.
const segmenter = new Intl.Segmenter('en', { granularity: 'grapheme' });
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
const seen = new Set();
const result = [];
for (const [name, text] of groups) {
  const items = [];
  for (const { segment } of segmenter.segment(text)) {
    const item = byKey.get(keyOf(segment));
    if (!item) {
      console.warn(`no Apple image: ${segment}`);
      continue;
    }
    const key = keyOf(segment);
    if (seen.has(key)) continue;
    seen.add(key);
    copyFileSync(join(source, 'img/apple/64', item.image), join(out, `${key}.png`));
    // The fully qualified form, as Apple devices type it.
    items.push(String.fromCodePoint(...item.unified.split('-').map(code => parseInt(code, 16))));
  }
  result.push({ name, items });
}

const body = result
  .map(group => `  { name: '${group.name}', items: ${JSON.stringify(group.items)} },`)
  .join('\n');
writeFileSync(
  join(root, 'frontend/src/components/crm/emojiSet.ts'),
  `// Generated by scripts/build-emoji.mjs from emoji-datasource-apple. Do not edit by hand.\n` +
    `export const emojiGroups: { name: string; items: string[] }[] = [\n${body}\n];\n`,
);
console.log(`${seen.size} emoji, ${readdirSync(out).length} files`);
